export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return <div style={{ width: '100%', height: '100%' }}>{children}</div>
}
